//
//  FirestoreSchema.swift
//  Soulverse
//
//  Central definition of all Firestore collections, subcollections,
//  and Firebase Storage paths used in the app.
//
//  ┌─ users/{uid}                          (FirestoreUserService)
//  │   ├─ mood_checkins/{checkinId}        (FirestoreMoodCheckInService)
//  │   └─ drawings/{drawingId}             (FirestoreDrawingService)
//  │
//  └─ Storage: users/{uid}/drawings/{drawingId}/
//      ├─ image.png                        (rendered drawing)
//      ├─ recording.pkd                    (PKDrawing binary data)
//      └─ thumbnail.png                    (future: Cloud Functions)
//

import Foundation

// MARK: - Firestore Collections

/// All Firestore collection and subcollection names.
/// Use these instead of hardcoded strings in service classes.
enum FirestoreCollection {

    /// Top-level collection for user profiles.
    /// Path: `users/{uid}`
    static let users = "users"

    /// Subcollection for mood check-in records under a user.
    /// Path: `users/{uid}/mood_checkins/{checkinId}`
    static let moodCheckIns = "mood_checkins"

    /// Subcollection for drawings under a user.
    /// Path: `users/{uid}/drawings/{drawingId}`
    static let drawings = "drawings"
}

// MARK: - Firebase Storage Paths

/// File names and content types for Firebase Storage.
/// All drawing files are stored at: `users/{uid}/drawings/{drawingId}/{fileName}`
enum StorageFile: String, CaseIterable {

    /// Rendered drawing image (PNG).
    case image = "image.png"

    /// PencilKit drawing recording binary data.
    case recording = "recording.pkd"

    /// Thumbnail image, generated by Cloud Functions (future).
    case thumbnail = "thumbnail.png"

    /// MIME content type for this file.
    var contentType: String {
        switch self {
        case .image, .thumbnail:
            return "image/png"
        case .recording:
            return "application/octet-stream"
        }
    }

    /// Builds the full Storage path for this file.
    /// - Returns: `users/{uid}/drawings/{drawingId}/{fileName}`
    func path(uid: String, drawingId: String) -> String {
        return "users/\(uid)/\(FirestoreCollection.drawings)/\(drawingId)/\(rawValue)"
    }
}
