# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a dev build to Testflight"
  lane :development do |option|
    increment_build_number(xcodeproj: "Soulverse.xcodeproj", skip_info_plist: true)
    version_num = get_version_number(xcodeproj: "Soulverse.xcodeproj", target: ENV["SCHEME"])
    build_num = '100' + get_build_number(xcodeproj: "Soulverse.xcodeproj")
    build_app(workspace: "Soulverse.xcworkspace", scheme: ENV["SCHEME"], configuration: "Debug")
    api_key = app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_ISSUER_ID"],
      key_filepath: ENV["API_KEY_FILEPATH"]
    )
    upload_to_testflight(
      skip_submission: true,
      api_key: api_key
    )
  end

  desc "Push a release build to Testflight"
  lane :release do |option|
    increment_build_number(xcodeproj: "Soulverse.xcodeproj", skip_info_plist: true)
    version_num = get_version_number(xcodeproj: "Soulverse.xcodeproj", target: ENV["SCHEME"])
    build_num = '300' + get_build_number(xcodeproj: "Soulverse.xcodeproj")
    build_app(workspace: "Soulverse.xcworkspace", scheme: ENV["SCHEME"], configuration: "Release")
    api_key = app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_ISSUER_ID"],
      key_filepath: ENV["API_KEY_FILEPATH"]
    )
    upload_to_testflight(
      skip_submission: true,
      api_key: api_key
    )
  end

  desc "Test upload existing IPA to TestFlight"
  lane :test_upload do
    api_key = app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_ISSUER_ID"],
      key_filepath: ENV["API_KEY_FILEPATH"]
    )
    upload_to_testflight(
      skip_submission: true,
      ipa: "/Users/mingshing/Soulverse/Soulverse.ipa",
      api_key: api_key
    )
  end
end
